name: Deploy

# Trigger the workflow on push and pull request events on the live_server branch
on:
  push:
    branches: ["live_server"]
  pull_request:
    branches: ["live_server"]

# Jobs should be top-level, not nested under `on`
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/weldfoxfolder/weldfox
            ./.scripts/deploy.ssh
